Feat/add hpu support
BlueLabelLabs/CLIP-habana pull request #1
Opened 2024-12-19 02:03 UTC by PiotrBLL

2025-01-14 19:59 UTC, sjagtap1803 commented on clip/clip.py
> +    # patch dtype to float32 on CPU, HPU
What datatype is being used here by default? Is it bf16?

If so, have you tried running the model in bf16 on hpu?

2025-01-20 12:25 UTC, BartoszBLL commented on clip/clip.py
> +    # patch dtype to float32 on CPU, HPU
![image](https://github.com/user-attachments/assets/242d5ba5-2e1d-476f-a50a-25c206f13c08)
Here is the screenshot of model params dtypes - as you can see they are torch.float16 and torch.float32.

I haven't run the model in bf16, as some operations implemented in CLIP explicitly cast tensor type to float32:
```
class LayerNorm(nn.LayerNorm):
    """Subclass torch's LayerNorm to handle fp16."""

    def forward(self, x: torch.Tensor):
        orig_type = x.dtype
        ret = super().forward(x.type(torch.float32))  << HERE
        return ret.type(orig_type)
```

I could experiment with modifying those to use bf16 and verify the compatibility of this exact tensor type and overall CLIP inner workings if you'd find this beneficial.
Let me know

2025-01-21 16:30 UTC, sjagtap1803 commented on clip/clip.py
> +    # patch dtype to float32 on CPU, HPU
Thanks for sharing this. I don't think we need to change inner working of CLIP if the inference with float32 is fast enough.

2025-01-28 17:22 UTC, orionsBeltWest requested changes

2025-01-28 17:22 UTC, orionsBeltWest commented on README.md
> +image_input = preprocess(image).unsqueeze(0).to(device)
missing: 

Reading image via the PIL package! See original README in repo.

2025-01-28 17:22 UTC, orionsBeltWest commented on requirements_hpu.txt
> +optimum-habana==1.14.1
Wondering where are optimum-habana modules are used?

2025-01-28 17:54 UTC, BartoszBLL commented on README.md
> +image_input = preprocess(image).unsqueeze(0).to(device)
Fixed in [859a140](https://github.com/BlueLabelLabs/CLIP-habana/pull/1/commits/859a140c046fd6b6858317398688cdfd65cb9779)

2025-01-29 12:49 UTC, BartoszBLL commented on requirements_hpu.txt
> +optimum-habana==1.14.1
as mentioned by Piotr yesterday, it is needed for habana_frameworks

2025-02-11 17:05 UTC, orionsBeltWest requested changes
I know clip is installed but some how in path in container is broken:

root@6019147233fe:/workspace/clip# python -c "import clip"
/usr/lib/python3.10/inspect.py:288: FutureWarning: `torch.distributed.reduce_op` is deprecated, please use `torch.distributed.ReduceOp` instead
  return isinstance(object, types.FunctionType)
Loading Habana modules from /usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/lib
Exception ignored in atexit callback: <built-in method cleanup of PyCapsule object at 0x7fc1e03e8210>
RuntimeError: Habana device not initialized
root@6019147233fe:/workspace/clip#

2025-02-11 17:05 UTC, orionsBeltWest commented on tests/test_consistency.py
>  import clip
please add some instructions on how run the test. 

when running test I was prompted to import 
pytest 
clip

I pip installed pytest. 

for clip its probably path issue?

2025-02-11 18:40 UTC, orionsBeltWest requested changes, later dismissed

2025-02-11 18:40 UTC, orionsBeltWest commented on benchmark.py
> +    end_time = time.time()
Please use perf_counter for start and end time as below. 

end_time = time.perf_counter()

2025-02-11 18:40 UTC, orionsBeltWest commented on benchmark.py
> +    image = transform(Image.open("CLIP.png")).unsqueeze(0).to(device)
please time this block after removing image read call to outside the timing call.

2025-02-11 18:40 UTC, orionsBeltWest commented on benchmark.py
> +    with torch.no_grad():
also time this block and compare with timing to send image to device. 

Simply need to take image io out of the timing loop.

2025-02-12 13:05 UTC, BartoszBLL commented on benchmark.py
> +    with torch.no_grad():
@orionsBeltWest I excluded image io and added 10 model runs (on the same image, as I think it accomplish the same thing - correct me if I'm wrong) as requested.

---
>also time this block and compare with timing to send image to device.

I'm not sure if I understand. What should be compared?

2025-02-12 13:11 UTC, BartoszBLL commented on tests/test_consistency.py
>  import clip
Sorry about the pytest, forgot to push local changes to requirements.txt

>for clip its probably path issue?

You should install clip either via `pip install git+https://github.com/openai/CLIP.git`  or `pip install -e .`.
I've added `pip install -e .` command to Dockerfile, so it shouldn't throw this error again.

2025-02-12 13:13 UTC, BartoszBLL commented on benchmark.py
> +    end_time = time.time()
Changed in [07c9771](https://github.com/BlueLabelLabs/CLIP-habana/pull/1/commits/07c9771a30d70171a29357d9e959115f92b1749e)

2025-02-12 13:13 UTC, BartoszBLL commented on benchmark.py
> +    image = transform(Image.open("CLIP.png")).unsqueeze(0).to(device)
Changed in [07c9771](https://github.com/BlueLabelLabs/CLIP-habana/pull/1/commits/07c9771a30d70171a29357d9e959115f92b1749e)

2025-02-12 13:13 UTC, BartoszBLL commented on tests/test_consistency.py
>  import clip
And info on how to run tests is added to README.

2025-02-12 16:20 UTC, orionsBeltWest commented
When running the new bench mark, I am getting cpu time better than hpu time!

INFO:__main__:HPU time: 0.1586 seconds
INFO:__main__:CPU time: 0.0674 seconds

2025-02-12 16:21 UTC, orionsBeltWest commented
I could run the pytest and but I do not see the gaudi initialization banner! Are these tests utilizing the gaudi?

2025-02-20 19:23 UTC, orionsBeltWest commented
I was able to verify the benchmark scrip when I ran it on the bluelable cluster! 

However, found that it runs very slow due to reinitializing the gaudi for each run.   Hence I would recommend this verion:

```
import logging
import time
import numpy as np
import torch
from PIL import Image

import clip
from clip.utils import get_device_initial

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


#def run_model(model_name, device):
def run_model(model, image, text, device):

    with torch.no_grad():
        start_time = time.perf_counter()

        logits_per_image, _ = model(image, text)
        probs = logits_per_image.softmax(dim=-1).cpu().numpy()

        end_time = time.perf_counter()
        logger.info(f"Execution time: {end_time - start_time:.4f} seconds")
    return probs, end_time - start_time


def run_n_times(model_name, device, n):
    times = []
    logger.info(f"Running {model_name} on {device} {n} times")
    model, transform = clip.load(
        model_name, device=get_device_initial(device), jit=False
    )

    image = transform(Image.open("CLIP.png")).unsqueeze(0).to(device)
    text = clip.tokenize(["a diagram", "a dog", "a cat"]).to(device)
    for _ in range(n):
        logger.info(f"Run {_ + 1} of {n}")
        #_, time = run_model(model_name, device)
        _, time = run_model(model, image, text, device)
        times.append(time)
    return np.mean(times)


if __name__ == "__main__":
    hpu_time = run_n_times("RN50", "hpu", 10)
    cpu_time = run_n_times("RN50", "cpu", 10)

    logger.info(f"HPU time: {hpu_time:.4f} seconds")
    logger.info(f"CPU time: {cpu_time:.4f} seconds")
```

2025-02-24 15:33 UTC, orionsBeltWest approved these changes

2025-02-24 16:07 UTC, merged